### ISSUE TITLE
Export button not working in ICE

### ISSUE THREAD

**Issue by aruffinABF** [JBEI/ice#65]
I'm trying to download all plasmid sequences from the R. toruloides parts folder. I have checked all the plasmids and clicked on Export > CSV & Sequences, but nothing happens. There is an error reported in the upper right of the screen: Unknown server error. See screenshot below.

![image](https://user-images.githubusercontent.com/33553796/33079512-03f5b70e-ce93-11e7-815b-2a3214518c52.png)

**Comment by Zulko** [comment]
We have the same problem, and below are the logs ("No such file or directory"). Not sure what is going on I don't read java logs very well. Could it be that it fails at writing a file, for instance because of writing rights ?

```
 09:55:49.952 [http-nio-8080-exec-10] ERROR org.jbei.ice - No such file or directory
ice_1       | java.io.IOException: No such file or directory
ice_1       | 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
ice_1       | 	at java.io.File.createTempFile(File.java:2024)
ice_1       | 	at org.jbei.ice.lib.entry.EntriesAsCSV.writeList(EntriesAsCSV.java:143)
ice_1       | 	at org.jbei.ice.lib.entry.EntriesAsCSV.setSelectedEntries(EntriesAsCSV.java:78)
ice_1       | 	at org.jbei.ice.services.rest.FileResource.downloadCSV(FileResource.java:306)
ice_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ice_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ice_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ice_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
ice_1       | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
ice_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
ice_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
ice_1       | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
ice_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
ice_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
ice_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
ice_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
ice_1       | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
ice_1       | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
ice_1       | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
ice_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
ice_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
ice_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
ice_1       | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
ice_1       | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
ice_1       | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
ice_1       | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
ice_1       | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
ice_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
ice_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
ice_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
ice_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
ice_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ice_1       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
ice_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
ice_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
ice_1       | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
ice_1       | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
ice_1       | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
ice_1       | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
ice_1       | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
ice_1       | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
ice_1       | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
ice_1       | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
ice_1       | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
ice_1       | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
ice_1       | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
ice_1       | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
ice_1       | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
ice_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ice_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ice_1       | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
ice_1       | 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by hplahar** [comment]
On the admin settings page, are the temp and data directories set correctly?

**Comment by Zulko** [comment]
Possibly not, I'll check next week and report back. Thanks !
